/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mperry' at '17/10/14 1:38 PM' with Gradle 2.1
 *
 * @author mperry, @date 17/10/14 1:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
